version: "3.9"

services:
  child_container_1:
    image: ubuntu-task2:latest
    cap_add: 
      - all
    volumes: 
      - /sys/kernel/security:/sys/kernel/security
    command: ./exec.sh

  child_container_2:
    image: ubuntu-task2:latest
    cap_add: 
      - all
    volumes: 
      - /sys/kernel/security:/sys/kernel/security
    security_opt:
      - apparmor=tmp_mount_access
    command: ./exec.sh
  
