version: "3.9"

services:
  parent_container:
    image: ubuntu-task2:latest
    cap_add: 
      - all
    volumes: 
      - /sys/kernel/security:/sys/kernel/security
      - /var/run/docker.sock:/var/run/docker.sock
    command: ./start.sh
  
